<a href="https://colab.research.google.com/github/KimJunGu9/ADP_ML/blob/main/1_LinearRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# 회귀분석 개념

# 하나 혹은 그 이상의 원인이 종속변수에 미치는 영향을 추적하여 식으로 표현하는 통계기법
# 변수들 사이의 인과관계를 밝히고 모형을 적합하여 관심있는 변수를 예측하거나 추론하기 위해 사용하는 분석 방법

In [2]:
# from sklearn.linear_model import LinearRegression

#  LinearRegression은 계수 w = (w1, …, wp)를 사용하여 선형 모델을 피팅한다
#  선형 모델은 X_train 으로 선형 근사에 의해 예측된 선형 회귀식과 y_train 사이의 잔여 제곱합을 최소화한다


# LinearRegression() : 선형회귀분석 모델을 생성하는 함수
# fit() : 선형 회귀 모델에 필요한 두 가지 변수(x, y)를 전달


# 설명변수의 차원을 조정해야 함
# R의 summary()와 같은 기능이 없음
# 기울기와 절편을 따로 호출해서 얻을 수 있음
# 잔차를 자동으로 계산해주는 기능이 없음
# model.coef_ 로 회귀계수 추출가능

In [4]:
# Ridge

# Ridge 회귀는 L2 정규화로 계수 크기에 페널티를 부과하여 일반 최소 제곱의 일부 문제를 해결합니다.
# 매개변수 : alpha = 1.0



# Lasso

# Lasso는 L1 정규화로 희소 계수를 추정하는 선형 모델입니다.
# 매개변수 : alpha = 1.0



# ElasticNet

# Elastic-Net은 계수의 L1 및 L2 정규화로 훈련된 선형 회귀 모델입니다.
# alpha = 1.0 , l1_ratio=0.5

In [7]:
import pandas as pd 
import numpy as np 

In [9]:
from keras.datasets import boston_housing
(X_train, y_train), (X_test, y_test) = boston_housing.load_data()

In [10]:
print(X_train.shape)
print(y_train.shape)

(404, 13)
(404,)


In [11]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(X_train, y_train)

LinearRegression()

In [12]:
print('기울기 :', lr.coef_)
print('절편 :', lr.intercept_)

기울기 : [-1.19997513e-01  5.70003304e-02  3.98379660e-03  4.12698187e+00
 -2.05002963e+01  3.38024903e+00  7.56807584e-03 -1.71189793e+00
  3.34747537e-01 -1.17797225e-02 -9.02318039e-01  8.71912756e-03
 -5.55842510e-01]
절편 : 40.29367058057694


In [13]:
# 추정된 값을 보기 위해서는 모델.predict(x)를 출력한다

y_pred= lr.predict(X_test)
y_pred

array([ 9.69267239, 21.05859431, 20.94145461, 34.25223414, 25.95902598,
       20.56741038, 28.15310405, 25.07113862, 20.30519458, 22.82489511,
       20.29027213, 18.07938917, 16.46141024, 35.31166595, 19.41369959,
       19.34727116, 24.58140904, 21.01346252, 19.99079236, 23.79286427,
       12.20780045, 17.14218992, 22.51468752, 12.92570511, 21.18070615,
       23.94073547, 33.46176314, 24.2631555 , 13.35213096, 20.71939252,
       23.45082103, 19.1486881 , 36.09743765, 23.47113531, 19.03141995,
        5.92425733, 14.02090469, 22.96425377, 16.01731242, 27.09134249,
       22.06997029, 28.61755389, 17.75679772, 34.75579014, 31.29455712,
       24.73234165, 31.12655323, 18.09268992, 22.62638989, 24.21208909,
       30.5854317 , 18.71860574, 10.50163617, 13.73779292, 34.4022841 ,
       27.53140317, 18.08151522, 40.05101982, 37.63271513, 24.64021422,
       25.73823434, 20.64369987, 20.33514699, 21.38393124, 24.63485497,
       23.53071805, 17.42141466, 26.76911736,  3.83782148, 11.97

In [14]:
# 잔차를 확인하는 방법 : y값과 추정값의 차를 계산
# 기존에 있던 값이랑 추정한 값의 차이가 바로 잔차이다.


resid= y_test - y_pred
resid

array([ -2.49267239,  -2.25859431,  -1.94145461,  -7.25223414,
        -3.75902598,   3.93258962,   3.04689595,  -2.17113862,
         0.19480542,   0.37510489,  -1.69027213,  -3.57938917,
         1.33858976,  14.68833405,   1.38630041,   4.95272884,
        -0.38140904,  -1.21346252,  -0.89079236,  -1.09286427,
        -0.20780045,  -6.94218992,  -2.51468752,   5.57429489,
        -0.28070615,  -0.94073547,  -5.96176314,   5.8368445 ,
        -3.85213096,   1.28060748,  -2.25082103,  -5.0486881 ,
        -2.99743765,  -0.07113531,   1.06858005,   1.47574267,
         1.37909531,   0.83574623,   4.08268758,  -2.59134249,
        10.93002971,  -0.21755389,  -3.65679772,  11.94420986,
         1.20544288,   4.86765835,  -2.72655323,   1.70731008,
        -2.42638989,   0.78791091,   4.8145683 ,   1.58139426,
        -0.80163617,   0.76220708,   0.4977159 ,  -0.93140317,
       -10.88151522,   9.94898018,  -5.23271513,  -3.04021422,
         4.06176566,  -7.54369987,   7.16485301,  -0.18

In [15]:
# R2 

print("훈련 데이터 셋 성능 : ", lr.score(X_train,y_train))
print("테스트 데이터 셋 성능 : ", lr.score(X_test,y_test))

훈련 데이터 셋 성능 :  0.7399643695249463
테스트 데이터 셋 성능 :  0.7213535934621551


In [16]:
#mse 

(resid**2).sum()/len(y_test)

23.195599256422994

In [17]:
# rmse 

np.sqrt((resid**2).sum()/len(y_test))

4.816180982523704

In [28]:
# boston data 집값이 평균적으로 4.8 차이가 난다.
# 예측된 집값이 가지고있던 집값보다 4.8차이가 난다고본다,

# r2의 값이 높을수록 rmse 값이 낮아짐 

In [18]:
from sklearn.metrics import mean_squared_error

mse = mean_squared_error(y_test,y_pred)
rmse = np.sqrt(mse)

print(mse)
print(rmse)

23.195599256422994
4.816180982523704


In [19]:
# R2 값이 훈련데이터에 비해 테스트 데이터셋이 더 작으므로 과대적합임을 알 수 있다.
# R2 값이 0.721은 좋은 성능은 아니다.
# 모델의 성능을 높이려면, 과대적합을 조정해주어야 함

In [20]:
X_train

array([[1.23247e+00, 0.00000e+00, 8.14000e+00, ..., 2.10000e+01,
        3.96900e+02, 1.87200e+01],
       [2.17700e-02, 8.25000e+01, 2.03000e+00, ..., 1.47000e+01,
        3.95380e+02, 3.11000e+00],
       [4.89822e+00, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        3.75520e+02, 3.26000e+00],
       ...,
       [3.46600e-02, 3.50000e+01, 6.06000e+00, ..., 1.69000e+01,
        3.62250e+02, 7.83000e+00],
       [2.14918e+00, 0.00000e+00, 1.95800e+01, ..., 1.47000e+01,
        2.61950e+02, 1.57900e+01],
       [1.43900e-02, 6.00000e+01, 2.93000e+00, ..., 1.56000e+01,
        3.76700e+02, 4.38000e+00]])

In [21]:
# 다중공선성의 문제 있을 수 있다. 


from statsmodels.stats.outliers_influence import variance_inflation_factor

vif_list = []
for i in range(X_train.shape[1]): 
    vif_list.append([variance_inflation_factor(X_train,i)])
vif_list


[[1.9881877151979828],
 [2.804118579367551],
 [14.145753573906159],
 [1.125530342044093],
 [73.08329671342511],
 [76.61643270931764],
 [22.825374214058293],
 [15.680198501096752],
 [16.922433536136374],
 [67.03752350696183],
 [82.6002684911088],
 [19.408593504685076],
 [10.373716006715824]]

In [22]:
vif_dt = pd.DataFrame(vif_list,columns=['vif'])

In [23]:
vif_dt[vif_dt['vif']<10]

vif
0  1.988188
1  2.804119
3  1.125530

In [24]:
# Ridge, Lasso, ElasticNet

# Ridge, Lasso, ElasticNet 은 모두 alpha값에 영향을 받는다.
# alpha 값을 통해 과대적합을 피할 수 있다.
# 하지만, alpha 값이 너무 크면 과소적합이 될 수 있으므로 최적의 값을 찾아야 한다

In [25]:
# GridSearchCV

# 모델에 지정된 매개변수 값에 대해 주어진 목록을 탐색 하여주는 함수이다.

# sklearn.model_selection.GridSearchCV(estimator, param_grid, cv=None)

# 예시 ) parameters = {'kernel':('linear', 'rbf'), 'C':[1, 10]}

In [26]:
# Ridge

In [27]:
import warnings
warnings.filterwarnings(action='ignore')

from sklearn.linear_model import Ridge 

In [30]:
ridge = Ridge() 
ridge.fit(X_train,y_train)

Ridge()

In [31]:
# r2
 
print("사용한 데이터 컬럼 수 :", np.sum(ridge.coef_!=0))
print("훈련 데이터 셋 성능 : ", ridge.score(X_train,y_train))
print("테스트 데이터 셋 성능 : ", ridge.score(X_test,y_test))

사용한 데이터 컬럼 수 : 13
훈련 데이터 셋 성능 :  0.7368910658116572
테스트 데이터 셋 성능 :  0.7291312320284361


In [34]:
# alpha = 1로 하였을 때, r2 0.7291임을 알 수 있다.
# LinearRegression 모델의 0.7214 보다는 성능이 좋지만 Ridge의 최적화된 값임은 알 수 없다.

In [35]:
from sklearn.model_selection import GridSearchCV

ridge = Ridge() 
param_grid = {'alpha':(0.0001,0.0005,0.001,0.005, 0.01,0.05,0.1, 0.15, 0.2, 0.25, 0.3,0.5,1,2,3)}

model = GridSearchCV(ridge, param_grid)
model.fit(X_train,y_train)

GridSearchCV(estimator=Ridge(),
             param_grid={'alpha': (0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05,
                                   0.1, 0.15, 0.2, 0.25, 0.3, 0.5, 1, 2, 3)})

In [36]:
model.best_estimator_

Ridge(alpha=0.2)

In [37]:
model = Ridge(alpha=0.2) 
model.fit(X_train,y_train)

Ridge(alpha=0.2)

In [38]:
# r2
 
print("사용한 데이터 컬럼 수 :", np.sum(model.coef_!=0))
print("훈련 데이터 셋 성능 : ", model.score(X_train,y_train))
print("테스트 데이터 셋 성능 : ", model.score(X_test,y_test))

사용한 데이터 컬럼 수 : 13
훈련 데이터 셋 성능 :  0.7396633685011149
테스트 데이터 셋 성능 :  0.724402334425835


In [39]:
# Lasso

In [40]:
from sklearn.linear_model import Lasso

lasso = Lasso() 
lasso.fit(X_train,y_train)

Lasso()

In [41]:
# r2

print("사용한 데이터 컬럼 수 : ", np.sum(lasso.coef_!=0))
print("훈련 데이터 셋 성능 : ", lasso.score(X_train,y_train))
print("테스트 데이터 셋 성능 : ", lasso.score(X_test,y_test))

사용한 데이터 컬럼 수 :  10
훈련 데이터 셋 성능 :  0.6716953935430134
테스트 데이터 셋 성능 :  0.6898070950696362


In [42]:
# Lasso의 경우 Ridge와는 다르게 사용하는 데이터 컬럼 자체를 0으로 만들어 변수 선택법과 같이 삭제를 해줄 수 있다.
# 위의 결과값의 경우 훈련데이터셋 자체에 성능이 낮으므로 과소적합이 되었음을 알 수 있다.
# 과소적합을 해결하기 위해 alpha값을 조정한다.

In [43]:
lasso = Lasso() 
param_grid = {'alpha':(0.0001,0.0005,0.001,0.002, 0.003, 0.005, 0.01,0.05,0.1, 0.15, 0.2, 0.25, 0.3,0.5,1,2,3)}

model_lasso = GridSearchCV(lasso, param_grid)
model_lasso = model_lasso.fit(X_train,y_train)

print("best_model: ", model_lasso.best_estimator_)

best_model:  Lasso(alpha=0.005)


In [44]:
from sklearn.linear_model import Lasso

lasso = Lasso(alpha=0.005) 
lasso.fit(X_train,y_train)

Lasso(alpha=0.005)

In [46]:
# r2

print("사용한 데이터 컬럼 수 : ", np.sum(lasso.coef_!=0))
print("훈련 데이터 셋 성능 : ", lasso.score(X_train,y_train))
print("테스트 데이터 셋 성능 : ", lasso.score(X_test,y_test))

사용한 데이터 컬럼 수 :  13
훈련 데이터 셋 성능 :  0.7398557492173086
테스트 데이터 셋 성능 :  0.7239074699892882


In [47]:
# 13개의 데이터를 사용하고 패널티를 적용하였을 때, Lasso의 경우 0.7239의 설명력을 가짐을 알 수 있다.

In [48]:
# ElasticNet

In [49]:
from sklearn.linear_model import ElasticNet

elastic = ElasticNet()
elastic.fit(X_train,y_train)

ElasticNet()

In [50]:
# r2

print("훈련 데이터 셋 성능 : ", elastic.score(X_train,y_train))
print("테스트 데이터 셋 성능 : ", elastic.score(X_test,y_test))

훈련 데이터 셋 성능 :  0.679487679418803
테스트 데이터 셋 성능 :  0.6962304506212673


In [51]:
elastic = ElasticNet() 
param_grid = {'alpha':(0.0001,0.0005,0.001,0.005, 0.01,0.05,0.1, 0.15, 0.2, 0.25, 0.3,0.5,1,2,3), 
              'l1_ratio' : [0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8, 0.9]}
              
model_elastic = GridSearchCV(elastic, param_grid)
model_elastic.fit(X_train,y_train)

GridSearchCV(estimator=ElasticNet(),
             param_grid={'alpha': (0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05,
                                   0.1, 0.15, 0.2, 0.25, 0.3, 0.5, 1, 2, 3),
                         'l1_ratio': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8,
                                      0.9]})

In [52]:
print("best_model: ", model_elastic.best_estimator_)
print("훈련 데이터 셋 성능 : ", model_elastic.score(X_train,y_train))
print("테스트 데이터 셋 성능 : ", model_elastic.score(X_test,y_test))

best_model:  ElasticNet(alpha=0.001, l1_ratio=0.4)
훈련 데이터 셋 성능 :  0.7395191600007747
테스트 데이터 셋 성능 :  0.7250350896059556


In [53]:
model_elastic =  ElasticNet(alpha=0.0001, l1_ratio=0.4)
model_elastic.fit(X_train,y_train)

ElasticNet(alpha=0.0001, l1_ratio=0.4)

In [54]:
print("사용한 데이터 컬럼 수 : ", np.sum(model_elastic.coef_!=0))
print("훈련 데이터 셋 성능 : ", model_elastic.score(X_train,y_train))
print("테스트 데이터 셋 성능 : ", model_elastic.score(X_test,y_test))

사용한 데이터 컬럼 수 :  13
훈련 데이터 셋 성능 :  0.7399582057760252
테스트 데이터 셋 성능 :  0.7218329276404374


In [57]:
# 13개의 데이터 컬럼을 사용하고 패널티를 적용하였을 때, Elastic의 경우 0.7218의 설명력을 가짐을 알 수 있다.

In [58]:
model_elastic.coef_

array([-1.19763491e-01,  5.71081357e-02,  2.22382974e-03,  4.11880823e+00,
       -2.00835139e+01,  3.38477900e+00,  7.21815023e-03, -1.70560242e+00,
        3.34101343e-01, -1.18317657e-02, -8.97531743e-01,  8.75231330e-03,
       -5.56216927e-01])